#ifndef OPCODE_H
#define OPCODE_H
#define OP_ADD		1
#define OP_ADDI		2
#define OP_SHIFTL	3
#define OP_SHIFTR	4
#define OP_AND		5
#define OP_NOP		6
#define OP_NOT		7
#define OP_OR		8
#define OP_XOR		9
#define OP_B		10
#define OP_BEQ		11
#define OP_J		12
#define OP_JEQ		13
#define OP_LB		14
#define OP_LW		15
#define OP_LWL		16
#define OP_LWR		17
#define OP_SB		18
#define OP_SH		19
#define OP_SW		20
#define OP_SWL		21
#define OP_SWR		22
#define OP_FADD		23
#define OP_FSUB		24
#define OP_FMUL		25
#define OP_FDIV		26
#define OP_FZERO	27
#define OP_FABS		28
#define OP_FNEG		29
#define OP_FCMP		30
#define OP_BEQF		31
#define OP_JEQF		32
#define OP_JLINK	33
#define OP_LINK		34
#define OP_PUSH		35
#define OP_POP		36
#define OP_SAVE		37
#define OP_RESTORE	38
#define OP_SAVEH	39
#define OP_RESTOREH	40
#define OP_OUT		41
#define OP_FLW          42
#define OP_FSW          43
#endif
